services:
  - type: web
    name: smart-ai-website
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    healthCheckPath: "/healthz"
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false   # set in Render dashboard
